"""Type stub for pyngrok — not installed locally, only used in Colab."""
from typing import Any

class NgrokTunnel:
    public_url: str
    def __str__(self) -> str: ...

def connect(port: int, **kwargs: Any) -> NgrokTunnel: ...
def disconnect(public_url: str) -> None: ...
def kill() -> None: ...
